CREATE TABLE event
(
  DESCRIPTION VARCHAR(150),
  EVENT_DATE DATE,
  IMPORTANCE INT(1),
  EVENT_ID BIGINT(20) AUTO_INCREMENT,

  PRIMARY KEY(EVENT_ID)
);

CREATE TABLE person
(
  FIRST_NAME VARCHAR(20),
  SURNAME VARCHAR(100),
  MAIL VARCHAR(100),
  PASSWORD VARCHAR(15),
  PERSON_ID BIGINT(20) AUTO_INCREMENT,

  PRIMARY KEY(PERSON_ID)
);

CREATE TABLE EVENT_TO_PERSON
(
  PERSON_ID BIGINT(20) NOT NULL,
  EVENT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (PERSON_ID, EVENT_ID)
);